// Lambda Node.JS
'use strict';
var Alexa = require("alexa-sdk");

exports.handler = function (event, context, callback) {
	var alexa = Alexa.handler(event, context);
	alexa.registerHandlers(handlers);
	alexa.execute();
};

const handlers = {
	//Launch the Skill
	'LaunchRequest': function () {
		var welcomeMessage = 'Welcome to the Oracle of Kwan Yin, a Chinese fortune telling practice found in some Buddhist temples. ... I will help you draw a lot from a bamboo cup found on the altar. ... ... First, relax your mind and meditate on your wish. ... After the bamboo cup stops shaking, say what\'s my fortune. ... Ready? ... Let\'s begin. <audio src="https://s3.amazonaws.com/alexasoundsdigitalsandbox/rattleSFX.mp3"/>';
		this.emit(':ask', welcomeMessage, 'Please try again. Think of your wish and say what\'s my fortune?');
	},
	//What fortunes are possible
	'FortuneIntent': function() {
		var fortune = [
			//Lot 1
			"Lot 1: A GOOD Fortune  \nAt the time the world began, all things were preordained.  A favorable day brings each fruit to ripeness.  Tis not uncommon that such a happy lot is drawn:  By loyal and upright - the King will proclaim.  \nMeaning: This lot refers to the creation of the world.  It portrays prosperity in all things.  There is good fortune in store for you, though not just yet.  \nRecommendation: Do not be reckless.  In due course all will be well.  Thus is the advice of the Buddha.",
			//Lot 2
			"Lot 2: An OK Fortune  \nThe baby fish stays quiet in the river while growing.  Don\'t aim too high or try to jump too far.  One day in the future, your body will change and grow; In one bound you\'ll clear the dragon\'s lair.  \nMeaning: This lot describes a young fish waiting patiently and unhurriedly.  Similar, you must put up with everything and stretch your patience to its limit, till the right moment comes.  In this way, you may retain your honor and reputation. \nRecommendation: Be patient.  Act when you are capable.  Success will follow.",
			//Lot 3
			"Lot 3: A BAD Fortune  \nAgainst the driving rain the traveller returns: Just like a swallow homing to her nest.  With clay she builds a rampart to keep out the rain.  The rampart falls and is reduced to clay - so all is wasted.  \nMeaning: Just as a swallow tries to build a nest with clay against the rain, your effort will be made in vain.  Trying every means and working day and night, who can tell that eventually all efforts turn out to be fruitless.  \nRecommendation: The mind is not free of worries day and night.  To act will bring misfortune.",
			//Lot 4
			"Lot 4: An OK Fortune  \nA mirror, though broken one thousand years ago can be put together again.  The man and his wife, having divorced, will re-unite.  Settling up their new home, they lead a happy life. And bring comfort and joy to their off-spring.  \nMeaning: A broken mirror can be pieced together.  All efforts made to make up for the past mistakes will bring forth good fruit.  Shift the sand and find gold.  Ride on the dragon and trample the tiger.  For all your efforts, you will be rewarded.  \nRecommendation: Time to change to new ways so that the family status will progress.  Future generations might benefit exponentially.  One can succeed if one does not stop working.  Hope is high.",
			//Lot 5
			"Lot 5: An OK Fortune  \nDig deep in the ground in search for water:  With pain and hardship you must fight your way through.  Then all of a sudden you meet an old friend.  Who brings you up to the blue sky of heaven.  \nMeaning: A man digs the field in the hope of finding water.  After much hardship, you will find that the thing you want can be obtained with ease.  What you seek can be found in the west.  Everything will be at hand as long as you do not move.  \nRecommendation: Before one does anything important, look at the four cardinal points.  Better to let things be for the present.  In time, all will be well.",
			//Lot 6
			"Lot 6: An OK Fortune  \nMake your home in the cave with the birds as your companions.  Be contented with yourself and be jealous of none.  Each man can stand by himself and make his own living.  None is so lucky as to travel over the world.  \nMeaning: This scene shows a man having only birds for company.  You must lead your life in accord with your lot.  Food will be scanty, so you must learn to be content and lead a simple life.  Be patient and enjoy what you have.  Let others pursue wealth and power.  \nRecommendation: A true martyr is rare.  One must first die before one can be called on.  Be prepared for the impossible if you seek to undertake what you are hoping to do.  Worrying and thoughts tend to confuse.  A tranquil mind will succeed.  Success, if achieved, is great.",
			//Lot 7
			"Lot 7: A BAD Fortune  \nYour way ahead is blocked and barred.  The streams are bearing earth and clay.  If you explore in foreign places, you\'ll find no work, no home to rest.  \nMeaning: In this scene, a boat is being tossed and dragged along through muddy water.  You must stand firm and make no move.  Since progress cannot be made, withdrawal and retreat will become necessary.  Let things stay as they are. Aim at nothing ambitious and you will not fail.  \nRecommendation: Best to stick to present situation for to carry on would be bad. Have no hope for betterment yet.",
			//Lot 8
			"Lot 8: A GOOD Fortune  \nPine and cypress thrive and flourish: No rain or snow, wind or frost can do them harm.  One day the timber will prove its value.  You are like such timber, a bulwark of society.  \nMeaning: This lot describes a scene of abundant cypress and pine trees. They symbolised human prosperity and dignity.  You will enjoy a safe and easy journey and achieve success in your career.  The grain and silk crop will be abundant.  The prestiage of your family will continue to grow, so will your wealth.  \nRecommendation: The coast is clear.  Your deeds please people.  Your efforts get good return.  Joy, peace and stability for the family.",
			//Lot 9
			"Lot 9: An OK Fortune  \nYield not to greed and hate: cast them aside.  Let conscience be your only guide.  Your heart will be open pure, sublime and bright.  Just like the full moon that shines high in the sky.  \nMeaning: This lot depicts a full moon lighting up the sky.  Everywhere is lit up with the brightness of hope.  Be as upright, unbiased and impartial as you can and uphold the principles of reason, justice and mercy.  No saint or sage ever yields to injustice and corruption.  Darkness and light can always be distinguished.  \nRecommendation: Do not be selfish lest you be prosecuted.  Only good will follow you if you are good to others and your career.",
			//Lot 10
			"Lot 10: An OK Fortune  \nA treasure house of jade and gems awaits you:  Why search in foreign lands for unknown gold?  Like the man who holds the lamp and seeks for fire:  Better pack your bags and set our for home.  \nMeaning: A man holds a lamp and still looks for fire.  You should be patient and wait for your opportunity.  Success will be at hand.  Be satisfied with what you have.  Don\'t waste your energy on hopeless dream.  What is in front of you is real and genuine.  \nRecommendation: Make hay while the sun shines.  Be alert to take advantage of the right situation and be selective lest you make mistakes.",
			//Lot 11
			"Lot 11: A GOOD Fortune  \nTo gain a victory is a rare event:  Among the family there is bitter strife.  By luck, the arrow will hit the running deer:  A savior will be found to lead the way.  \nMeaning: In this scene, misfortune turns out to be fortune.  What ever you plan to do will be successful.  Changes and upheavals lie ahead, but no one will be harmed.  If you need consultation and guidance, consult your noble patron.  \nRecommendation: Proper effort will lead to success.  A Benefactor is likely to render service.",
			//Lot 12
			"Lot 12: A GOOD Fortune  \nBetween good and evil the span is short: When misfortune is past, good luck will be yours.  Befriend a gentleman that lives by the mountain:  For you, he has good news to relieve your concern.  \nMeaning: Good fortune will follow misfortune.  Go ahead with your business and things will turn out well.  Instead of hemp, you will receive silk to adorn your legs.  Blessing will come after disaster, as your destiny has already been determined.  \nRecommendation: Sack-cloth turns to silk to cling to your feet.  In time, will you understand -- As one lives, one flourishes.",
			//Lot 13
			"Lot 13: A GOOD Fortune  \nYou were born to a noble family: Your future will be pomp and ease.  The King will grant you a golden mantle - Your fame, your glory will never subside.  \nMeaning: All paths lead to the golden gate.  Everything is in motion but turns out to your benefit.  Prisoners will be pardoned and the sick cured.  Once you reach the golden gate, your frame will spread over the Royal capital and will never be forgotten.  \nRecommendation: The prisoner is free.  Sickness cured.  Having reached the Dragon-gate, one\'s name becomes famous.",
			//Lot 14
			"Lot 14: A GOOD Fortune  \nThe fairy crane escapes from its cage.  So you can fly wherever you will.  No corner of heaven is barred on your flight.  Even to Paradise, or as far as you please.  \nMeaning: In this scene, a fairy crane escapes from its cage.  So all things turn out to be lucky.  Everything is laid out for you.  You may choose as you please.  There is no danger.  You should relax, take your time and never grumble.  \nRecommendation: One\'s thought is just as above.  When one\'s on a smooth road, so is one\'s desire.  So too, is a man of ease.",
			//Lot 15
			"Lot 15: An OK Fortune  \nThe man on foot is smitten by the brazen sun. A disaster of nature befalls upon you unaware.  Like a bird whose nest has fallen.  You\'ll find shelter only in the hidden depth of the forest.  \nMeaning: Like a bird seeks a nesting place in the forest, you will encounter hardship and difficulty at first, but all your troubles will be over in the end.  If someone has offended you, when will you take revenge?  Because sweet words offend the ear, tolerance is your only path.  \nRecommendation: A person who follows wrong advice could not do right.  He could not differentiate right from wrong, good from bad.  Best to stick to the present situation.",
			//Lot 16
			"Lot 16: An OK Fortune  \nDon\'t wear a mournful face with drooping eyes: Put aside all cares and think of joy.  A piece of jade is found in a heap of dung - The craftsman cleans the jade and it gleams as new.  \nMeaning: This lot depicts the phenomenon of harmony of Yin and Yang.  When the two principles are in harmony - as in this lot - your plans will work our successfully.  What you have gain will not be lost, and for what you have lost you will be compensated.  A villain will experience misfortune as punishment, but the virtuous man will be rewarded with good luck.  \nRecommendation: An evil person beware, if you get this Fortune.  What is yours, is assured to be yours.  Difficult at first, with proper applied skill, success follows.",
			//Lot 17
			"Lot 17: A BAD Fortune  \nTurn a deaf ear to scandal and gossip: By day and night just chant the prayers to Buddha.  If you believe the lies and malicious talks, you're supping on meals of fantasy.  \nMeaning: This lot derives from a Chinese proverb in which a man satisfies his hunger by drawing a cake.  It is something vain and hopeless.  It is a waste to say prayers if you heart is full of discontent and distraction.  You draw a cake to satisfy your hunger, but you remain hungry.  \nRecommendation: One\'s mind is full of trouble.  Even the Scriptures will be misunderstood.  A picture of a cake can not be eaten.",
			//Lot 18
			"Lot 18: A GOOD Fortune  \nFar in the horizon, the Crow falls, the Rabbit rises:  Day and night succeed each other since the world began.  Believe in Buddha and the Tao, all is wisdom.  Be you scholar or peasant, worker or merchant.  \nMeaning: The Crow symbolizes the Sun, the Rabbit symbolizes the Moon.  The rising and the setting of the sun and the moon symbolize the ups and downs of human life.  Harmony between sun and moon is a sign of prosperity.  Remain calm in heart.  All you look for can be achieved.  An arrow once shot from its bow can pierce asunder all the way through.  \nRecommendation: Do not worry. Be firm and receive success.  Like a well-aimed arrow, it meets the target.",
			//Lot 19
			"Lot 19: An OK Fortune  \nA home-bound ferry rolls and pitches in the swirling gorges:  The wind and the waves surge and roll - But to what end?  Stability and calm cannot be found:  Wait till the angry waves rest in peace.  \nMeaning: A boat is carried rolling through swirling rapids.  You must be patient and wait for the right moment to come.  Nothing can be done while the situation is precarious, as when a boat is borne through the rapids.  But when the time is favorable, seize your chance and press ahead.  \nRecommendation: For the present moment, some difficulties.  Be patient and wait a while.",
			//Lot 20
			"Lot 20: A GOOD Fortune  \nThe long rain ends, the sky is clear - joy for all!  The sun and moon gradually becomes bright.  Gone are the days of sadness; be happy and gay:  With only one leap you\'ll clear the Dragon Gate.  \nMeaning: This lot describes the sky brightening up after long rain.  It means that everything will turn out to be favorable.  Under the protection of gods and Buddhas, on one will be harmed, whatever are the circumstances.  Once your long-cherished ambition is realized, your homecoming will be a glorious one.  \nRecommendation: The situation is right.  Proceed.  It is just the beginning.",
			//Lot 21
			"Lot 21: A GOOD Fortune  \nBlessed is the union of the man and his wife.  Who marry in accord with Yin and Yang.  So the dragon and a serpent join together: United are they in a dream so sweet.  \nMeaning: This describes the harmony of the sun and the moon.  It symbolises great good fortune.  Whatever you wish will materialize.  \nRecommendation: Do as you plan.  In marriage: a male offspring.  Fortune and crops increase.",
			//Lot 22
			"Lot 22: A GOOD Fortune  \nIn time of drought, the stems in the paddy fields wither and fade.  Thank Heaven, a heavy shower comes in due time.  Then flower, fruit and grass are watered well - A timely rain is worth its weight in gold.  \nMeaning: This lot describes rain falling after a long drought.  Whenever you are in difficulty, someone will come to your rescue.  You\'ll reap a better crop of grain and silk, because Good Fortune is knocking at your door.  \nRecommendation: Silk and harvest three-fold fortune and time is good.  Medical help to cure sickness.  A safe return from travelling.",
			//Lot 23
			"Lot 23: A GOOD Fortune  \nYou try to reach the moon and climb the laurel tree: Alas!  The Gate of Heaven is shut and access is denied.  But good news will suddenly spread. Then all will be happy and put on smile.  \nMeaning: This lot describes a man trying to pluck a branch from a fairy laurel tree.  It means that someone of fame and high standing will come to your rescue when you are in trouble.  All the profits will go to the merchant and traders.  Your own career will be in danger.  \nRecommendation: Business facing some difficulties will flourish.  Sickness cured.  Civil cases won.  Do as you planned.",
			//Lot 24
			"Lot 24: A BAD Fortune  \nYour home is broken up by disputes without a cause: Like withered blossoms drifting on a bottomless ocean.  Grace will hardly aid an idiot or a fool: A heap of trouble is all that remains.  \nMeaning: In this scene, a fool is trapped and can find no way out. In such a situation, you can do nothing but put up with your difficulties. Tolerance can work miracles. Breath no gossip and spread no scandal: Look after everything carefully.  Be as hardworking, honest and friendly as you can.  In this way, you will keep yourself out of disaster.  \nRecommendation: Do not be bothered about whether a subject is true or false.  Be alert in what you do.  To succeed, keep a firm desire.",
			//Lot 25
			"Lot 25: A GOOD Fortune  \nThe days of hardship and danger are gone:  Plans revived will work well and prosper.  A broad mind works out effective schemes:  Talent seen by your patrons will earn its reward.  \nMeaning: This lot describes the scene of an old well being replenished with spring water.  Anything you do will be patronized by nobles and dignitaries who will help to bring your plans to fulfilment.  Your grievances will finally be answered.  Diseases are cured and a time of happiness begins.  Just as an old well is replenished with spring water, so you will overcome the difficulties you encounter.  \nRecommendation: Sickness will be cured.  What you are attempting will produce a well giving sweet water.",
			//Lot 26
			"Lot 26: A BAD Fortune  \nRumour spreads among the court attendants: From Heaven comes a special message, offering rank and honour to your name.  Alas!  Totally, untrue and groundless it proves to be.  \nMeaning: This lot describes the emptiness of name and tilte.  Like pomp and human vanity, they are empty and worthless.  So you should be more realistic and true to your own nature.  A man is concerned about his name and rank.  They are nothing but sham.  Why concern yourself with rank and title?  Better stand back and attend to your own affairs.  \nRecommendation: You could not seek peace of mind any way you tried.  You hope to succeed.  Stick to the present.",
			//Lot 27
			"Lot 27: A GOOD Fortune  \nYour plans are drawn up with care.  But fear and hesitation prevent you from putting them into effect.  When the time matures, there will come your noble patron who will assist you to put up a comfortable home.  \nMeaning: In this scene, strong fences guard a secure and peaceful residence:  So you may enjoy peace of life without risk.  Let old things be converted into new, like Spring providng warmth to flowers suffering from Winter cold.  The former days of sorrow are past, and you should be as relax as your can.  \nRecommendation: Out with the old, in with the new! Flowers bloom again in spring.  Your performance seems meaningless, yet you\'ll find it suits you.",
			//Lot 28
			"Lot 28: An OK Fortune  \nThe moon rises in the east, so full of grace and beauty;  Concealed from sight but still in place.  Sometimes rising, sometimes full, it runs in course.  Gossips are still gossips, not a word of truth they say.  \nMeaning: The moon is overshadowed by clouds, so all things seem obscure, dim and unsettled.  The cloud that covers the moon is only fleeting; so don\'t worry or draw back.  It will soon pass.  Once the clouds disperse, all things will be clear and forward move.  \nRecommendation: Do not fear the present.  After circumstance change, all will be well again.",
			//Lot 29
			"Lot 29: A GOOD Fortune  \nThe sacred sword, unsheathed, will shine and glitter:  No dust or filth has touched the brightness of its surface.  A man of noble rank takes hold of it now:  Such chivalry is envied by all men.  \nMeaning: This depicts a sacred sword being drawn from its sheath and signifies a show of pomp and grandeur of gallantry and bravery.  When the sacred sword is drawn, its fame will spread far and wide.  And the nobleman who bears this sword will be met with favour and popularity.  \nRecommendation: One is appreciated even from afar.  A Benefactor comes along to teach.  Future dealings lead to success.",
			//Lot 30
			"Lot 30: A BAD Fortune  \nDon\'t aim too high - The best of my advice:  A stork in flight may conceal a secret arrow.  As you collect sticks for fuel in the field, you may find a snake.  Much you will grieve for that bite from the venom.  \nMeaning: This lot advises you to be content and hold yourself back from too high an ambition.  You must take every precaution against possible adversities.  Keep your mouth as tight as a sealed bottle.  Don\'t get involved but remain aloof.  For anything done against your conscience, you will eventually suffer incalculable harm.  \nRecommendation: Shut up, grind your teeth, mind your own business.  If you have evil desire, you are likely to hurt yourself.",
			//Lot 31
			"Lot 31: An OK Fortune  \nYou will lead a life of ease and peace:  You will have no cause for worry or concern.  Relax!  When the meal is done, enjoy a sip of tea:  Be sure!  No grief or misery will come.  \nMeaning: You are advised to take things easy and remain calm without bothering for change.  Everything will turn out well if you are patient enough.  Remain calm and free from anxiety.  You may as well ask advice from fairies.  Patience and tolerance will work miracles for you.  Nothing can be achieved till the time is ripe.  \nRecommendation: Let things be.  All will be well as a result.  Be patient you who consult the Buddha as time.  Success follows.",
			//Lot 32
			"Lot 32: An OK Fortune  \nYour journey is long and places are unknown:  Who can foretell the rock conceals a piece of jade?  One day the craftsman\'s skill will bring it out.  The priceless gem is yours, the joyful owner!  \nMeaning: A piece of jade is found within a stone.  This means success can only be achieved through unfailing efforts.  A priceless jade is embodied inside a rock.  Such notion may meet with laughter.  The skill of an experienced mason may prove it.  But when that comes true, you can do whatever you wish.  \nRecommendation: Within rocks, blessings.  Few knew this.  Only when one fully understand the problem, then it is safe to go on.",
			//Lot 33
			"Lot 33: An OK Fortune  \nYou\'re unaware that things of value are within reach:  So around and around you look in vain hope.  Be relaxed and wait for the man to come:  For he can tell where is the treasure hidden.  \nMeaning: A man is looking everywhere for gold without knowing a piece of jade is concealed in a rock nearby.  You must be patient and wait for a favorable time to come.  Gold and jade are concealed somewhere;  you search everywhere but with no result. Fortune will come to your aid and you will receive all you justly deserve.  \nRecommendation: One possess jewels, yet is ignorant about their value.  A jeweller appraises it and then only one learns its true value.",
			//Lot 34
			"Lot 34: A GOOD Fortune  \nBe courteous and humble in conduct of life;  Your words honest and your behavior sincere.  If doubt is harbored in your heart, be straight and upright, like the rays of the sun.  \nMeaning: The red sun is hanging in the middle of the sky.  It signifies your wishes will be fulfilled.  Like water in autumn, clean, pure and tranquil:  So your heart should be calm and free of care.  Why bother with doubts and worries when things can be worked out without difficulty?  \nRecommendation: No trouble within oneself. Let one mind be pure and clear as the crystal water of the lake. Understanding will follow.",
			//Lot 35
			"Lot 35: An OK Fortune  \nYour hats and coats must be adjusted:  Restore the family name, now in bad shape.  Remove the thorns and thistles, pave the way:  When agreement is reached, great will be your reward.  \nMeaning: This lot describes people dressing up in rich and formal costumes to uphold the family\'s name.  Hardship must come before your wishes can be fulfilled.  Doubts and fears lead to nothing:  Better wait for your lucky day.  Be bold and set off on your journey, because ahead of you is a wider avenue of opportunity.  \nRecommendation: Do not worry.  Good times are near.  To benefit in future advance.",
			//Lot 36
			"Lot 36: An OK Fortune  \nYou are sick and involved in law: stay calm.  Resources and riches await your exploration.  A doughty monkey frees himself from a golden chain.  Roaming about in freedom in his mountain cave.  \nMeaning: A clever monkey makes an escape from a golden chain.  It signifies that difficulties and hardship can be overcome with effort.  Once your worries and troubles are over, nothing is beyond your power.  A man of patience will be highly rewarded:  The road of success is open in front of you.  \nRecommendation: There is really no trouble.  Rest your mind.  Wait for a good chance, then you are free to advance further.",
			//Lot 37
			"Lot 37: A BAD Fortune  \nDon\'t dare expose yourself to the naked sun:  The burning candle barely flickers in the wind.  It\'s best to retire and hide in distant lands:  Follow the life of a hermit and enjoy blissful peace.  \nMeaning: A lighted candle flickers precariously in the wind.  You should retreat from an unfavorable situation.  Keep away from risk and lead a secure and peaceful life.  Retire to a quiet and secluded place.  You are advised to do nothing but wait.  Any movement may bring danger and harm, so your only guard is to remain calm.  Keep your present home unchanged and no risk will come to you.  \nRecommendation: Seek solitude in a calm quiet place to get away from the storm.  If one is reckless, evil will result.  Best to stay as you are.",
			//Lot 38
			"Lot 38: A BAD Fortune  \nYou long for words from heaven to fall from the moonlit sky:  Dim it is and darkened by the racing clouds.  Let not your heart be burden with sorrow and care:  The clouds will pass and you will begin anew.  \nMeaning: The moon in the sky is overshadowed by clouds and mist.  You need to be patient.  Time is not ripe to achieve your ambitions.   \nRecommendation: Family in trouble.  People have no peace.  People might even use the Buddha\'s advice to cheat you.",
			//Lot 39
			"Lot 39: A BAD Fortune  \nThe message is sent from the distant horizon.  Its meaning is obscure, just nonsense and worthless.  A stone cannot be turned into a mirror:  So be wise - don\'t waste your time, but save your labor.  \nMeaning: TThis is a parable about the impossibility of turning a stone into a mirror.  You should not be so foolish as to attempt something beyond your ability.  You must be content with your lot and keep things as they are.  All efforts will turn out in vain, though you have made a thousand plans.  So patience and contentment should be the golden rule.  \nRecommendation: Many futile attempts.  Revert to the past situation.  Do not seek trouble.",
			//Lot 40
			"Lot 40: A GOOD Fortune for women specifically  \nAs the sun sets, the moon will rise:  The lunar power grows, the solar power wanes.  If it be a woman seeking fortune, she will be blessed with joy all the year.  \nMeaning: This describes the moon over-shadowing the sun.  The meaning is that once difficulties are overcomed, progress becomes plain sailing.  Blessing will go to woman, not to man, becuase the moon\'s influence is ascending.  Your wishes will first be rejected, but granted in the end.  \nRecommendation: The time for female dominance.  What one hopes will be peace at first, followed by prosperity and success.",
			//Lot 41
			"Lot 41: A BAD Fortune  \nBeware of sweet and honeyed words:  That twist and spoil your paternal love.  Once you treat a thief as your son - An unwise deed you\'ll regret hereafter.  \nMeaning: This is a parable of a man who is tricked into treating a thief as if he were his own son.  It warns you to be watchful not to be deceived by falsehood.  A single mistake may make you regret forever.  Remember this advice of mine and you will not feel sorry for being sacrificed.  \nRecommendation: Do not be deceived by one whom one thinks is good.  Be alert in body and soul, so as to be out of danger.",
			//Lot 42
			"Lot 42: A GOOD Fortune  \nFrom Kings and Queens is blessing received:  All honors saved and no faults laid. So you are blessed with Heaven\'s grace and favor. While still on earth you seem to repose in paradise.  \nMeaning: This lot describes a man who is privileged to receive gifts and favors from heaven.  It is of course an omen of good luck and achievement.  Never forget such a favor from heaven and remember your obligation to God.  So to show your gratitude towards the almighty, you should offer incense day and night.  \nRecommendation: The sky deity given you advice, from the beginning till the end.  Forget not let your heart be firm at all times and do worship.",
			//Lot 43
			"Lot 43: A GOOD Fortune  \nHeaven and Earth will work and change in concord:  For every creature, survival, growth and blessings.  In nature and in human life, there is beauty and wonder:  Such rewards of peace only saints and sages will bestow.  \nMeaning: This lot describes the phenomenon of heaven and earth working in harmony.  Everything is favorable and there is no threat of danger.  What you have done or planned to do will be blessed with good luck and fortune.  God\'s blessing and human virtue will give you your deserved reward and bring you success.  \nRecommendation: Give a good start to what one hope to achieve.  Luck and lasting beauty is upon you.",
			//Lot 44
			"Lot 44: An OK Fortune  \nDiamond cuts diamond.  The champion meets a worthy opponent:  How hard to say who will be victorious.  Each move is vital, each play is decisive.  So keep yourself from rash and foolish deeds.  \nMeaning: This lot depicts two diamonds set against each other, like a game of chess between two masters.  Final victory will go to the one who relies on his wit, prudence and strategy.  Consult a fortune teller about your chances.  Just as in a chess game, your fate depends on the next move you make.  \nRecommendation: To perform any task involves risk.  To overcome the next person, or to lose, one must possess some skill over him, or him over you.",
			//Lot 45
			"Lot 45: A GOOD Fortune  \nThe tender and meek shall conquer the violent and strong.  The kind-hearted will receive fathomless reward.  Their many deeds of kindness add up to so great merit:  The thirst of a man is quenched by juice of fairy seeds.  \nMeaning: By being always tender and kind towards people, you may gain great merit.  To know your future fully, you should bear in mind that your patron saint will always be ready to come to your rescue.  Heaven has great sympathy for your devotion.  By following the course of heaven, you may have protection and miracles may happen to you.  Such benevolence given to you must not be forgotten.  \nRecommendation: To perform any task involves risk.  To overcome the next person, or to lose, one must possess some skill over him, or him over you.",
			//Lot 46
			"Lot 46: An OK Fortune  \nMy advice is to stay still and make no change.  Be sure you take no action, nor new plan.  Be patient, for someone will soon come to help.  By then, a withered tree will blossom again.  \nMeaning: The flowering of a withered tree is an illustration of things accomplished in a natural way.  No human effort is therefore necessary.  Better stay quiet and keep things as they are with no change and no action.  Any move will bring with it misfortune.  \nRecommendation: It is wise not to crave for more as this will bring trouble.  For the present, stick to present state, and keep still.",
			//Lot 47
			"Lot 47: A GOOD Fortune  \nOn woven silk is embroidered a floral pattern:  As fate decrees, your rank and fortune will rise.  It is never too late to strive for honor and frame.  Once you have passed the Imperial Examination.  \nMeaning: This lot pictures the flowery pattern of embroidered silk.  It means that everything will be auspicious.  Wait and see if there is any change from the old to the new.  Following your parents wishes, you should cherish a life-long ambition.  It was by god\'s design that you pass the Imperial Examinations.   \nRecommendation: Do away with the old state.  A child being guided by wise parents.  Suit yourself in your endeavors.  Your livelihood is assured.",
			//Lot 48
			"Lot 48: A GOOD Fortune  \nA partridge is changed into a roc in autumn.  Such freedom is granted to no other bird.  Higher and higher it soars in the sky:  Mile of clouds he passes in its flight.  \nMeaning: This lot portrays a very rare scene in which a partridge is transformed into a roc - an enormous bird mentioned in the ancient legends.  Such a message means that a dramatic change is about to occur.  A partridge transformed into a roc - a very rare event indeed.  Especially for a game bird.  Pluck just one branch from a cassia tree, and your wealth and happiness will keep on growing.   \nRecommendation: One is lucky to get this prediction. Every good thing comes naturally.",
			//Lot 49
			"Lot 49: A BAD Fortune  \nSo cool is the water that is turned into ice.  So what is the purpose of honor and fame?  The best way left is to wait to see.  When the situation clears then it will come your time.  \nMeaning: This lot describes cold water turning into ice.  It means that all attempts at doing something beyond your ability will fail.  Cold water freezes into solid ice, and then becomes flowing water again.  Such a change is natural in the physical world, so it is in human affairs.  Man proposes, but god disposes.   \nRecommendation: Ice melts and freezes again.  Hoping to achieve something is futile.",
			//Lot 50
			"Lot 50: A GOOD Fortune  \nBorn on a voyage on the boundless ocean.  Sails hoisted high begin to billow and strain.  With winds behind to push the ship along:  Great chests of jewels and treasure will be yours.  \nMeaning: This lot describes a ship sailing in a favorable wind.  It signifies that everything will turn out to be favorable.  You lead a life of ease and comfort.  Rewards will come to you without much effort. As such a large fortune is entirely yours, people\'s gossip and envy will be aroused.   \nRecommendation: One\'s livelihood is good.  One spends no effort, yet one have lots of joy and money.",
			//Lot 51
			"Lot 51: An OK Fortune  \nDuring the long, long, tedious summer days each man is tortured by the scorching sun;  But now, a breeze, how soothingly does it blow!  It is the will of Heaven that caresses human souls.  As long as you can remain calm in a dilemma, to your rescue will come a saviour you can trust. So take the advice; Don\'t move with haste and recklessness. For if you do, you will become both a fool and a victim.  \nMeaning: This shows that anyone who can take it easy in times of trouble will find relief from grief and sorrow.  \nRecommendation: What you hoped to achieve, do so.  As you go on, good times come. Do not be reckless and observe caution.",
			//Lot 52
			"Lot 52: A BAD Fortune  \nSeeking the moon in the reflection of a pool is nothing but vain and hopeless distraction, so keep your tougue from gossip and scandal.  For no one will be fooled but you alone.  Empty words no one will trust.  To those that hear, they just bring harm.  Trouble awaits your kith and kin.  So hurry and seek a place to hide.  \nMeaning: Just as someone wastes his effort in trying to catch the moon\'s reflection in the water, so all endeavours a man makes will come to nothing.   \nRecommendation: You cannot understand what you hear.  You will not get return for you effort.  It will breed frustration.  Perhaps a Benefactor can solve your problem.",
			//Lot 53
			"Lot 53: A GOOD Fortune  \nMan, disappointed, turns complacent and self-satisfied.  Like the laughter of a tiger, like a triumph of a dragon.  From earth I see a milky way in the sky.  Rank and honor are clearly in your sight.  \nMeaning: Do whatever you have been instructed. Go ahead and don't harbour any disbelief. For the road to success is prepared for you. No troubles, no obstacles, all the way is clear.  \nRecommendation: If told to do, act at once.  If told to stop, stop.  Do this and it will bring happiness.  All your work is good.",
			//Lot 54
			"Lot 54: A BAD Fortune  \nAll is false, all avoid, nothing is real.  Things of value obtained only in a dream.  In marriage, in health, what future is there ahead?  Better look else where or dipped in distress.  \nMeaning: Things reflected in placid water.  Changing in shape and confused in order.  But in destiny all is preordained.  So no advice or guidance can be given.  \nRecommendation: Reflections on water tends to distort.  Look properly before one makes decision.  Be very careful.",
			//Lot 55
			"Lot 55: A GOOD Fortune  \nTo a good father will come so many sons.  Their food, their clothing Heaven will provide.  My parents live and prosper in health.  Let them eat and drink and sleep just as they choose.  \nMeaning: This scene depicts a pile of bamboo leading towards a stream.  A man\'s hope and aspiration will be realised at the final stages.  As bamboo poles standing in line lead to a large spring, Generation after Generation prospers and moves on.  As long as a man remains gentle and virtuous, whatever he wishes will come to hand.  \nRecommendation: Bamboo pipe conveying water towards one.  The deeds of the superior man pleases you.",
			//Lot 56
			"Lot 56: An OK Fortune  \nOn a rocky stream runs bubbling and shallow water: The men of state enjoy the breeze and silvery moonlight.  Seek out the way that marks your destiny.  The scent and sight of flowers should no distraction be.  \nMeaning: This describes a scene of sailing along a rapid stream.  It illustrates that great deeds can be accomplished only with strenuous effort.  A man puts all his energies on the project but achieves nothing, no matter how hard he tries.  So the best policy for him is to wait and see.  In the end things may turn out well for him.  \nRecommendation: One seek to achieve something. It will need trouble and effort. best to stick to present situation. You will be peaceful.",
			//Lot 57
			"Lot 57: A GOOD Fortune  \nTo rumor and scandal your ears should be shut, for your lot is a harvest of food and fine clothing.  Past sorrow and grievance be put out of your mind.  Place your trust in me and joy will be yours.  \nMeaning: This lot describes an infant under the devoted care and protection of the mother.  It illustrates that all is well looked after.  So you are completely free from worries.  Everyone rejoices at the plan's success. The happiness is shared by friends and relatives alike.  Don\'t be selfish but let the public affairs be your concern;  With the devotion a mother lavishes on her child.  \nRecommendation: For what you are praying, all is well.  Do cultivate constant effort.  Keep to the right way.  One is liken to a child meeting mother.",
			//Lot 58
			"Lot 58: A BAD Fortune  \nMy counsel to you is honest and plain:  Bear in mind.  Pursuit of trade in other lands is not your lot.  There is no better way to choose.  Remaining unchanged and in peace is the best course for you.  \nMeaning: This advises you to stay as you are and wait for a good opportunity.  As long as you are patient enough to wait, the chance will come.  Be satisfied and content with your lot.  For there is no better place to go.  If you attempt to make a further move, no blessing but misfortune will result.   \nRecommendation: Best to stop what one is doing and revert back.  Do not get involved in new ventures.  In time, all is well.",
			//Lot 59
			"Lot 59: A BAD Fortune  \nClimb up the tower to hide yourself away, as a man trapped in a jungle must hold this breath.  Fate will decree both good and bad.  Pity on you as the bad will prevail.  \nMeaning: This is a parable that advises you against dangerous move.  Stay firm as the final chance will come to your rescue.  Like a drunken man who has lost his legs.  Don\'t move but stand where you are.  Wait with patience till time will favor you.  For all will turn out well, with troubles gone.   \nRecommendation: One is drunk, yet drinks again.  Revert to the past.  When the time comes, worries and calamity will cease.",
			//Lot 60
			"Lot 60: A BAD Fortune  \nAs a fire is fed with added fuel, so the flames spread far and wide leaving nothing unscorched.  A fearful death awaits each one of us;  Not rank nor riches can save us now.  \nMeaning: This describes the scene of someone rushing to a burning house with firewood to put out the blaze.  You must take precaution against the possibility of being involved in a dangerous situation.   \nRecommendation: One\'s thoughts dwell on one thousand other things. One day, one realise that it is futlle.  Be quiet and calm and all will be well.",
			//Lot 61
			"Lot 61: An OK Fortune  \nBy daylight verses are recited, at night songs are sung.  On such an occasion let us savor these pleasures.  Making merry in life comes so seldom - So why do we hide and not junket together?  \nMeaning: This describes a scene of celebrations on festive days.  It tells you to take advantage of chances and opportunities.   \nRecommendation: A pretty maid singing, one feels glad.  Yet one\'s life seems to be lucky.",
			//Lot 62
			"Lot 62: A GOOD Fortune  \nBuddha is our guardian all hours of the day;  Only through him is danger averted.  With the help of a patron you are luck indeed.  For he will bring wealth and gold to your hands.  The situation is steady and stable, and your name is heard on all sides. When the program of changes is ready, all things will turn out as you desire.  \nMeaning: This depicts the scene of buddha\'s support from behind a screen.  You need not worry about anything but wait, and riches will come to hand.   \nRecommendation: Your life is level and peaceful.  Your name reaches the four quarters of the world.  The time is ripe for new ventures.",
			//Lot 63
			"Lot 63: A BAD Fortune  \nWhen last at sea, the compass was lost.  Today we sail again in search of same.  Though the first compass was later found, it is of no use now and all hope is drowned.  \nMeaning: This describes the search for a compass in the open sea.  All efforts are wasted and everything turns out to be hopeless.   \nRecommendation: Luck and fortune must have a good foundation that one rely on.  One must have merit to deserve it.  Would you heed things explained to you? Listen well before you act.",
			//Lot 64
			"Lot 64: A BAD Fortune  \nAs a fish is caught in a murky pond, around him a heavy net is drawn.  Here he darts, there he dashes, all the ways are blocked.  Each plan is worthless and in vain.  \nMeaning: The fish is caught in a net.  You must be very cautions so as not to fall into a trap.  \nRecommendation: One remains at home, yet the sea rains at one from the sky.  Be prepared for the worse.  A roof gives you shelter, yet you have no absolute safety.  At anytime a calamity may befall, so take precautions against all risks.",
			//Lot 65
			"Lot 65: A BAD Fortune  \nBe not content with the present joy.  Things as they stand are neither bad nor good. To cut the flesh to patch your wound - What foolishness!  Your wisest course is to make no change.  A man of prudence knows when and where to stop.  He will take measures both to retreat and to proceed.  Cutting a piece of flesh to patch the wound relieves no pain but brings himself to ruin.  \nMeaning: In this scene, a foolish man cuts his own flesh to patch his wound.  As a result, he only inflicts more pain upon himself.  \nRecommendation: Be content and stop if you should.  Loosen yourself if you need to loosen.  One is hurting one's self.",
			//Lot 66
			"Lot 66: A BAD Fortune  \nThe road is steep, the horses sliding down;  His platoon defeated, the soldier has gone astray.  Like a broken boat swept through gorges and rapids; So leaves are withered by frost and sunlight begins to fate.  \nMeaning: This scene depicts a wrecked boat being carried through surging current.  The whole situation is so dangerous that you must keep alert and take precautions. \nRecommendation: Best to do as you are doing now.  Be quiet and you experience peace.  Do not hope for good results.  Best to forget your problem.",
			//Lot 67
			"Lot 67: A GOOD Fortune  \nMaintain your metal balance the golden scale;  Bend not to favor nor lean to disgust.  Keep just, upright and stay the honest man.  With money or with man, hold on to this rule.  \nMeaning: A single strand of gold thread gladen one\'s heart.  One is at one with the universe.  Be a fair man so that one\'s status will heighten and one\'s achievement will be accepted and understood.  \nRecommendation: One is at peace, be fair.  One should prosper.  Do not be greedy and seek your contentment to enjoy earth\'s peace.",
			//Lot 68
			"Lot 68: A GOOD Fortune  \nA lucky day will bring great celebrations.  A family so generous, prosperity forever glows.  A fruitful year for farming and marriage.  And for the sick, cure comes at last.  The spring days are getting warmer, in a long line the flowers are blooming.  Don\'t waste your time in hesitation.  Your hopes and wishes will be realized.  \nMeaning: This is a scene of spring flowers in full blossom, with indication that all will prosper well. \nRecommendation: The day is cool and fine with myraid of flowers blooming.  Why do you fret when you seek will soon be yours?",
			//Lot 69
			"Lot 69: An OK Fortune  \nOn a lonely hill a plum tree shivers. Fallen leaves, withered twigs stand in the winter chill.  The warmth of spring returns so quietly.  Its beauty and its glory are both restored anew.  An arrow is dispatched but misses its target.  Don\'t be disappointed or lose hope.  But wait till your lucky day comes, then you will receive an enviable reward.  \nMeaning: The plum tree is restored to its prestige as the king of flowers.  You must not lose patience because things will turn out well for you in the end. \nRecommendation: One\'s aim will be accomplished although it seems futile at first.  One shoots an arrow to reach the void, but one could not succeed.  Finally, one does reach it.",
			//Lot 70
			"Lot 70: A BAD Fortune  \nThe busy bees fly from flowers to flower.  Each day their energy is consumed in frantic action.  When spring is gone and flowers begin to fade.  You\'ll have nowhere to go; stay where you are.  \nMeaning: Just as the busy bees must stick to the task of seeking food from the flowers.  So you must work hard each day to earn your living. \nRecommendation: When it shines, all is well.  But come rain, and it never stops raining, forget what one is doing and revert back.",
			//Lot 71
			"Lot 71: A BAD Fortune  \nWhen an old maid is married to two husbands, most likely the match won\'t succeed.  For how could a bow hold two arrows?  A dragon with a unicon will always quarrel.  It is all in the hands of god, no matter how desperate the battles go.  So stretch out your arms and draw the bow:  The arrow will shoot upward in one move.  \nMeaning: In this scene, a single bow is fitted with two arrows.  So disagreement is inevitable.  The solution lies in rearranging the misguided match. \nRecommendation: One has lots of worry.  Providence knows all.  Best to let things be for the time being and be cautious.",
			//Lot 72
			"Lot 72: A BAD Fortune  \nBees we raise for the sake of honey.  From time to time we are hurt by their stings.  To make a living there are other ways.  But many are the problems we never consider.  In every action you take, think it over many times, for heaven\'s sake.  It is only to make honey that we raise bees, so don\'t commit yourself too much if you want to be free.  \nMeaning: This describes the scene of raising bees for honey.  It means that money cannot be earned easily but only wth hard work. \nRecommendation: Observe caution in your dealings.  Do not be stubborn.  To gather good times is like a swarm of bees gathering honey.",
			//Lot 73
			"Lot 73: A GOOD Fortune  \nThe sudden thunder of spring awakes all worms and insects:  With joy, they chant in chours and jump from earth.  In winter deep in earth they lie, listless and slow: Set free, they are as active as a dragon released.  The roar of thunder quickens the wheel of fortune.  Circumstances have turned for the better.  Such a big change in a single day, like a somersault in front of heaven\'s gate.  \nMeaning: This is a description of the natural phenomenon of spring thunder waking up all the sleeping worms and insects.  It is indeed a good omen.  \nRecommendation: The season took a good turn.  Plenty of good things.  One day a great happening occur to even reach Heaven.",
			//Lot 74
			"Lot 74: A BAD Fortune  \nA snow gooes flies into a cage by chance -- Which is a prison, not a haven of safety.  As he sees the most precious part of freedom gone.  So will this lot\'s reader be sunk in remorse.  To go forward you may, but to withdraw leaves you in a sorry plight.  If you venture without careful thought, you will suffer a remorseful fate.  \nMeaning: In this scene, a snow goose plunges itself into a pond.  So things turn out to be vain and useless not valid and real.  \nRecommendation: To achieve anything needs great effort and concentration.  But even to achieve former status is hard.  Best to bow one\'s head and hope for betterment.",
			//Lot 75
			"Lot 75: A BAD Fortune  \nTo climb a mountain with a tiger as your companion.  You will shiver with fear every movement you make.  Good deeds in the past may bring you help.  With them, you may survive, both safe and sound.  Because of the dangers ahead, you must take all precautions. Someone may come and inquire of you.  There is nothing but pain right to the end.  \nMeaning: Just as the man climbing a high mountain together with a tiger, you will be confronted with danger and hardship.  \nRecommendation: One enquires about one\'s fate.  Danger lurks to the front.  No success except bad times.",
			//Lot 76
			"Lot 76: An OK Fortune  \nIn a swamp together live a fish and a dragon: Both hide in the deep, waiting for the lucky day.  Some day their chance will eventually come.  Over the Royal Dragon gate they pass in one leap.  Though you have laid a solid foundation, your favorable time is not yet come.  To wait and see is the best advice: To take risks is imprudent and crazy.  \nMeaning: This is a parable in which the fish and the dragon conceal themselves in the deep and wait for the change of a lucky fate.  \nRecommendation: One should have luck in future.  Be cautious for the present and be not reckless.  Wait.",
			//Lot 77
			"Lot 77: A BAD Fortune  \nYou make your fortune only in a dream;  An empty word comes from beyond heaven.  So fae and riches are too far to reach - Just follow your patron, and smiles will be yours.  Dreams are nothing but what you make them to be.  Fame is just an empty title.  My advice to you is to wait, and follow the lead of your patron.   \nMeaning: Just as treasure is only gained in a dream, so this lot advises you that high sounding promises are fictitious and unreliable.  \nRecommendation: Do not hope for non-existent objects and objectives.  Work for success in a more concrete and genuine way.",
			//Lot 78
			"Lot 78: A GOOD Fortune  \nDon\'t boil the water to scalding heat, Neither too cold nor hot: coolness is most fit.  You want to play a game of life that\'s fair - Best learn a trade that will be your support.  A criminal wins a gracious pardon.  A patient meets a good physician. If you seek to build up wealth, Rely on the instruction of your patron.  \nMeaning: This lot tells you not to go to extremes, as the middle way is the safest.  \nRecommendation: One is free.  Sickness will be cured by a skilled doctor.  Luck is around.",
			//Lot 79
			"Lot 79: An OK Fortune  \nA false vow is made before god.  You gain protection but fail to pay reward. God\'s words are holy and solemn - So flippant and fickle, how dare you be.  Each individual has his own principles;  Pay no heed to doctrines illogical.  What the Goddness of Mercy tells you to do, that you must follow through to the end.  \nMeaning: This lot tells you to aim at things real and practical and therefore, any pursuit of aimless objectives will end in failure.  \nRecommendation: One thinks one could achieve something.  Do not be trouble.  Kwan Yin tells you doubt not.  Heed the advice.",
			//Lot 80
			"Lot 80: A GOOD Fortune  \nYou are jealous of fairies and angels in flight;  Then, they name you an almighty king.  As sun and moon shine on you always, so will justice spread throughout the land.  Stick to your task from start to end, as strong and firm as your powers permit. No matter what you have in mind to do, there will come a saviour to lead you on.  \nMeaning: This predicts a scene in which a man of power and prestige leads you the way.  It illustrates that everything is in concord and harmony.  \nRecommendation: One is disciplined.  Advance on your new ventures.  There are many Benefactors around to aid.",
			//Lot 81
			"Lot 81: An OK Fortune  \nAutumn leaves being to fall from Phoenix Trees.  Tired travellers hurry home like migrating birds.  Grateful to almighty god who guards the returning folk. A ship laden with treasure sails home with favorable winds.  Whatever is your intention, Heaven will give it support. As man proposes, god disposes. So everything is kept in order and progress.  \nMeaning: The natural phenomenon of leaves falling from Phoenix Trees symbolizes that things may appear unfavorable at first, but will gradually improve.  \nRecommendation: Heaven will give their blessing to what you seek.  Proceed with what you are hoping to do.",
			//Lot 82
			"Lot 82: An OK Fortune  \nThe fierce flames give out a sorching heat, consumes all in its path - but not the water-lily.  Not burnt nor scorched by the flame, its leaves and fronds blossom ever again.  Rescue comes in face of danger. No fracture, no slight injury. For sure you have a savior standing by who guards you in all disasters.  \nMeaning: This lot describes the scene in which the water-lily survives the flames of fire and shows that you can reach safety through very hazardous conditions.  \nRecommendation: Though one meets danger, there is no harm.  A Benefactor will aid one in what one hopes to achieve.",
			//Lot 83
			"Lot 83: An OK Fortune  \nIn nature the moon must wax and wane:  On the 3rd or 4th of the month a crescent is seen.  By the 15th day she is round and full, making the sky so clear and bright.  Things change in a natural way, so be patient and wait for the time to come.  When the moon reaches its fullness, all will proceed as you desire.  \nMeaning: This describes the natural phenomenon of the moon appearing in a crescent.  It illustrates that in certain human affairs what appears precarious in the beginning is not so in the end.  \nRecommendation:  Wait till the time comes. Be patient.",
			//Lot 84
			"Lot 84: A BAD Fortune  \nVirtues spoilt by evil deeds:  The depraved and the evil must repay so high a price.  The drunkard, drowned in wine, knows nowhere to go.  All at a loss, he is so pitiful!  Like a chilly fish isolated from water:  A siutation for people to gossip and murmur.  If you want my advice, make no move to avoid being caught. \nMeaning: This depicts the scene of a chilly fish isolated from water.  Such a miserable situation indicates that one should remian calm and take no immediate action in times of woe.  Everything is unfavourable.  In a word, take precautions against misfortune.  \nRecommendation:  Like a fish out of water. Good is not actually good. Forget what you hope to do.",
			//Lot 85
			"Lot 85: An OK Fortune  \nThe clouds disperse; but the fog shrouds the way.  A family renunites and enjoys the full moon. As from an enchanting dream you awake, you will be lead to the Realm of Paradise.  To seek for pleasure in your declining age is like the final blossoming of spring.  If you desire both fame and wealth, a big fortune is waiting for you to claim. \nMeaning: This describes how flowers blossom again at the end of spring.  Things will change at a later date and prove more lucky and promising.  \nRecommendation:  An elder person had best wait till spring comes when their luck is due.",
			//Lot 86
			"Lot 86: A GOOD Fortune  \nSpring flowers glow with brightness on your balcony.  The chariots come, bringing loads of treasure. How swift a rise is yours to the highest.  A clap of thunder brings the world to heel.  To receive an appointment from the emperor is like a beggar suddenly made a millionaire.  As this special lot is a matchless offer, you shall obtain all you want with none to share.  \nMeaning: This scene describes a person going to court for an audience with the emperor. Everything is auspicious and works out for the best.  This lot is indeed the best of all, in a few words you may have whatever you wish and everything points to blessing and good fortune.  \nRecommendation: The king bestows one with honour.  A very poor person receives a priceless treasure.  Be content, this is indeed a good prediction.",
			//Lot 87
			"Lot 87: An OK Fortune  \nThe mountaineer strives to reach the middle ridge: The setting sun may leave him stranded.  He turns to heaven and asks god for help.  Amid cliff and crag, refuge has he now found.  Jade is found after chiseling the stone: Gold is found after sifting the sand.  Rely on no one, trust your effort alone: To attain a success, exercise your reason and mind.  \nMeaning: This scene describes a man who sifts and rinses the sand and then finds gold.  It is a good omen, meaning that a man of power and influence is always supporting you.  \nRecommendation: Jade is mined by crackling open huge rocks whilst gold dust is obtained by panning dirt. To do anything, use maximum effort and be firm.",
			//Lot 88
			"Lot 88: An OK Fortune  \nIn front of a gate a wooden tiger stands, looking so fierce but harmful to no one. It conjures up no threat of danger: So you have no need to fear to venture out.  Snow flakes fall on a hot stove; Whistling winds make the ears cold.  In fact they affect us so little: A change of fortune will solve it for you.  \nMeaning: The wooden tiger imposes a false impression by its appearance and imposing manner.  \nRecommendation: Running out of fuel for the fire, one feeds the fire with snow. Even the wind does not enter one\'s ear. Seek Buddha\'s help in time all will be well.",
			//Lot 89
			"Lot 89: A GOOD Fortune  \nYour plan, your schemes so smoothly carried out: Like jade of rarest kind concealed in stone.  A man of wealth and power will offer you his aid - The treasure and jewels are yours to keep.  As jade is hidden in a stone, wealth and fortune gradually grow.  A notable patron will lead the way for you: You are happy and have no more to say. \nMeaning: Just as the scene describes jewels hidden under a stone. So, you should be satisfied with the fortune in store for you. \nRecommendation: A Benefactor points out how to achieve it. Heed him. To achieve the possession of the jade will surely gladden one\'s heart.",
			//Lot 90
			"Lot 90: A GOOD Fortune  \nA special message drops from the sky: Ships laden with treasure will come by and by.  To know what lies ahead for you - The man from behind will support you all the way.  Looking towards your future career, I see a man of power is backing you.  The scene is full of joy and laughter: And everywhere abounds with wealth and treasure. \nMeaning: This describes a scene of both achievement and fame.  It advises you to keep on as you are and to go forward without unnecessary hesitation.  This lot can be summarized in two lines: All good wishes will be realised! Good fortune and luck will be yours always. \nRecommendation: One should have many helpers as one will have lots of food, money, and clothing, and so on.",
			//Lot 91
			"Lot 91: A GOOD Fortune  \nOpen your heart and distinguish yourself; A change of career will bring abundance of wealth.  In front a wide path is open to you.  Give all you can to the cause of charity.  Surging in an open boundless sea, the ship sails with a favorable wind.  Whatever you have in mind to do, go ahead boldly and give not a second thought. \nMeaning: A wide road leading to prosperity and position lies in the future.  Everything will progress smoothly and in your favor.  This is a favorable message which can be summarized as follows: Whatever you wish for will come true. Good luck and blessing will never desert you. \nRecommendation: Proceed with what you want to achieve. All is well.",
			//Lot 92
			"Lot 92: A GOOD Fortune  \nSince youth he has been a merchant of many years, having earned his fortune under many kings.  No one has helped him in his struggle up from a lowly commoner to a noble knight.  A man has grown up from his boyhood, and now stands firmly on his feet.  His mind he keeps constantly alert.  His reward is his present rank and honor. \nMeaning: A man has been a merchant since his boyhood.  Fortune can be achieved through diligence and frugality. \nRecommendation: From young to old, life is good. Suit yourself: success follows.",
			//Lot 93
			"Lot 93: A BAD Fortune  \nThe phoenix soft feathers are soaked with rain: Even a bird will not make a friend of him.  One day the rain will cease and the sky is bright again.  His plumage is now a regal feather-robe.  When vicious villians hold the stage, the virtuous and the noble men should retreat behind.  The day will come when things turn in their favor. They can do what they think is right. \nMeaning: This depicts the scene of the feathers of the mythical phoenix being soaked with rain.  It tells you that in time of misfortune you must tolerate all the humiliations inflicted upon you.  As soon as the rainy days are over, honour and glory will be regained. \nRecommendation: Evil is found everywhere.  A wise man would not interfere.  Silence is golden.  Wait till the time is due.",
			//Lot 94
			"Lot 94: A GOOD Fortune  \nThe virtuous stands apart from villians: Whose conduct will show their faults.  Fine music of the harp only tutored ears will know: Keeping up with the traditions will see you through.  You will find help only from a friend.  Who really knows and understands you.  Better keep yourself aloof from others: By doing so, you will be spared all pain and trouble. \nMeaning: You must look for a genuine friend, for no one except him can really help you.  You should observe all the traditions and practices and every thing will turn out right. \nRecommendation: One\'s thoughts must be agreeable with each other.  Do not cause trouble.  Wait till a Benefactor comes along.",
			//Lot 95
			"Lot 95: A GOOD Fortune  \nRome was not built in a day: Women and wine may block your way.  Retain your ambition, and display your merits. You will earn the king\'s favor and enviable pay.  Determine your objective and keep to it.  Diligence will eventually get its reward.  One day a golden pheasant brings joyful news, with it will come wealth and happiness. \nMeaning: An ambitious young man has made many achievements through determination and diligence.  This advises you to act according to customs and traditional practices.  In this way, fortune will sooner or later come your way. \nRecommendation: You having meditated deeply in time all will be well.  The Golden Rooster will help you.",
			//Lot 96
			"Lot 96: A GOOD Fortune  \nSeven storys high the majestic pagoda stands, in all directions it shines with glittering glow.  Devote yourself to worship and charity;  Heaven will reward your noble deeds.  This is your allotted share of happiness, good fortune is for all to see.  You have no cause for worry; Destiny has arranged your way ahead. \nMeaning: A virtuous man will be greatly rewarded with god\'s blessing.  With this lot you will be rewarded with fortune and luck. \nRecommendation: You have luck.  People see it.  Do not worry.  Many good times are ahead.",
			//Lot 97
			"Lot 97: A BAD Fortune  \nA candle in the wind casts fleeting shadows: Their reflections are like the blossom of willow trees.  A sailor on a floating raft waits for rescue, a party-goer whistles in the curfew-hour.  Wealth and fame are at the disposal of god: Fate decides on whom poverty will fall.  So to worry is a complete waste of effort, for everything is arranged by destiny. \nMeaning: The scene describes lighting a candle in the wind.  It is stuipid to aim for an empty title without substantial benefit. \nRecommendation: One is fated to be rich or poor. Poor and hardship do not contemplate on them.",
			//Lot 98
			"Lot 98: A BAD Fortune  \nSuspend your plan and action for a time: But idleness may give rise to scandal.  When birds fall into a waiting net.  The chance for them to be free is remote.  Just wait for your opportunity, the progress of time will bring you bliss.  The best advise to you is: Be patient and make no changes. \nMeaning: This advises you to remain where you are during unfavorable times.  Any move may result in trouble and woe.  \nRecommendation: Wait till a Benefactor comes to assist you. In asking for things, be patient.",
			//Lot 99
			"Lot 99: A BAD Fortune  \nThe rider who whips his horse but draws no rein will exhaust all the strength he has.  This is like a house being set on fire: the summer rain will reduce it to bricks and clay.  Working hard the whole life long, he cares not for right or wrong.  Shackles and fetters fall upon him suddenly. Thus, he is driven to a miserable fate. \nMeaning: This scene describes a situation which is neither good nor bad.  The best advice is to resort to kind deeds which may help to improve conditions for all concerned.  \nRecommendation: One had a hard life.  No good times. Do not meddle in people\'s affairs.  People will only give you trouble.  Misfortune comes naturally for you.",
			//Lot 100
			"Lot 100: A GOOD Fortune  \nProphecies of value god and buddha offer; led by the foolish, you pay them no heed.  As this the last lot you can choose, there\'s no luck for you to gain.  This is the last helpful message left for you:  All predictions are made and have proved true.  Remain unchanged and leave things as they stand; Wait patiently till your good chance comes.  \nMeaning: This lot advises you to take no action and let things move in their own way. Wait till the present situation changes in your favor.  Since this is the very last divine lot, there is no alternative way for you to follow.  You must be aware of one important thing: You are now in a very unfavorable situation and to overcome the present difficulties, you must pray to god for his gracious protection.  \nRecommendation: This is the last helpful message left for you; All predictions are made and have proved true.  Remain unchanged and leave things as they stand.  Wait patiently till your good chance comes.",
					 ];
			//end list of possible lots
		var rand = fortune[Math.floor(Math.random() * fortune.length)];
		var response = "<audio src='https://s3.amazonaws.com/alexasoundsdigitalsandbox/stickdropped.mp3'/>" + "..." + "This is the lot you\'ve drawn... " + rand + "..." + "Please refer to your Alexa app for a copy of your fortune today." + "..." + "..." + "Take a few moments and reflect on what you've heard." + "..." + "<audio src='https://s3.amazonaws.com/alexasoundsdigitalsandbox/zenbell.mp3'/>" + "May the Peace of Kwan Yin be upon you. ... Farewell for now.";
		var cardTitle = "From the Oracle of Kwan Yin";

 //How Alexa responds to "What's my fortune"
		this.emit(':tellWithCard', response, cardTitle, rand);
		},

//If Alexa does not know how to respond
	'Unhandled': function() {
		this.emit(':ask', 'Sorry, I didn\'t understand. Try saying what\'s my fortune.', 'Try saying what\'s my fortune.');
	},

//Help Intent - Triggered when asked "Help"
	'AMAZON.HelpIntent': function () {
		this.emit(':ask', 'Try saying what\'s my fortune.', 'try again');
	},

//Stop Intent - Triggered when told "Stop"
	'AMAZON.StopIntent': function () {
		var say = 'May the Peace of Kwan Yin be upon you. ... Farewell for now.';
		this.emit(':tell', say );
	},

//Cancel Intent - Triggered when told "Cancel"
	'AMAZON.CancelIntent': function () {
		var say = 'May the Peace of Kwan Yin be upon you. ... Farewell for now.';
		this.emit(':tell', say );
	}

}
